name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Check out
        uses: actions/checkout@v2
      - name: Run gofmt
        shell: bash
        run: |
          if ! test -z $(gofmt -l .); then
            echo "Some files are not formatted properly. Please run \"go fmt ./...\" and commit the changes."
            echo
            gofmt -d .
            exit 1
          fi
      - name: Run vet
        run: go vet ./...

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out
        uses: actions/checkout@v2
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
